# vim: set ts=2 sw=2 et:
# 
# Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# 
AWSTemplateFormatVersion: 2010-09-09
Description: Setup AWS IoT Policies and IAM Roles

Resources:
  IoTProvisioningRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: IoTProvisioning
      Path: /iot/
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSIoTThingsRegistration"
        - "arn:aws:iam::aws:policy/service-role/AWSIoTLogging"
        - "arn:aws:iam::aws:policy/service-role/AWSIoTRuleActions"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service: "iot.amazonaws.com"
            Action: "sts:AssumeRole"

  IoTAccess:
    Type: "AWS::IoT::Policy"
    Properties:
      PolicyName: IoTAccess
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 
            Sid: MQTTConnect
            Action:
              - "iot:Connect"
            Effect: Allow
            Resource: { "Fn::Join" : [ "", ["arn:aws:iot:",{ "Fn::Sub": "${AWS::Region}" },":", { "Fn::Sub": "${AWS::AccountId}" }, ":client/${iot:Certificate.Subject.CommonName}"]] }
          -
            Sid: MQTTRead
            Action:
              - "iot:Subscribe"
              - "iot:Receive"
            Effect: Allow
            Resource: "*"
          - 
            Sid: MQTTWrite
            Action:
              - "iot:Publish"
            Effect: Allow
            Resource: { "Fn::Join" : [ "", ["arn:aws:iot:",{ "Fn::Sub": "${AWS::Region}" },":", { "Fn::Sub": "${AWS::AccountId}" }, ":topic/${iot:Certificate.Subject.CommonName}"]] }

